# Setup
title:        Public Wiki
tagline:      A public wiki for the devolab!
baseurl:      "/public-wiki"
paginate:     1
locale:       "en"
permalink:    /:title/
# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com

# Define non-post collections
collections:
  journal_club:
    output: true

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
